version: "3.9"

networks:
  bridge:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      bridge:
        aliases:
          - zookeeper
    ports:
      - "32181:32181" # Expose Zookeeper port

  # kafka:
  #   image: confluentinc/cp-kafka
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENER_NAME_INTERNAL: INTERNAL://0.0.0.0:9093
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     JMX_PORT: 9999
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
  #   networks:
  #     bridge:
  #       aliases:
  #         - kafka
  #   ports:
  #     - "9092:9092" # Expose Kafka port

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_NAME_INTERNAL: INTERNAL://0.0.0.0:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
    networks:
      bridge:
        aliases:
          - kafka
    ports:
      - "9092:9092" # Expose Kafka port

  kafka-producer:
    image: kafka-producer
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      - bridge
    ports:
      - "3001:3001"

  flink-processor:
    image: flink-processor
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: "kafka:9092"
      ZOOKEEPER_SERVER: "zookeeper:32181"
      PRODUCER_INTERVAL: 100
    networks:
      - bridge

  client:
    image: client
    build:
      context: ./client # Assuming your Vite client code is in the `client` directory
    ports:
      - "5173:5173" # Expose Vite client on port 5173
    networks:
      - bridge
